// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edqdnpdinkcssvkpjzdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkcWRucGRpbmtjc3N2a3BqemR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTMyMzQsImV4cCI6MjA2MjYyOTIzNH0.ePoPHsAK4OJqVDXXJo9nvef62fGtYvWGZN0nhrhNqK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);